Data Cleaning

In [7]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
import math
 

# Read the CSV file into a pandas dataframe
oscar_df = pd.read_csv('oscar.csv')
df = pd.read_csv('combineddf.csv')

In [9]:
#Director Oscars

# Group the oscar dataframe by the name of the director and count the number of Oscars won
oscar_count_df = oscar_df.groupby('name').size().reset_index(name='oscars')

# Create a function that takes in a list of directors and returns the total number of Oscars won by them
def count_oscars(director_list):
    return oscar_count_df[oscar_count_df['name'].isin(director_list)]['oscars'].sum()

# Apply the count_oscars function to the "director" column in the "df" dataframe and store the result in a new column called "director_oscars"
df['director_oscars'] = df['director'].str.split(',').apply(count_oscars)

,imdb_score,place,title,year,synopsis,critic_score,people_score,total_reviews,rating,genre,...,NC-17,PG,PG-13,R,TV14,TVMA,TVPG,boxoffice,sentiment_score,director_oscars
0,8.303145,78,Avengers: Endgame,2019,"Adrift in space with no food or water, Tony St...",94,90,538,PG-13,"sci fi, adventure, action, fantasy",...,0,0,1,0,0,0,0,858400000.0,-0.7650,0
1,8.063783,199,Mad Max: Fury Road,2015,"Years after the collapse of civilization, the ...",97,86,427,R,"adventure, action",...,0,0,0,1,0,0,0,153600000.0,-0.7650,2
2,8.340630,66,Spider-Man: Into the Spider-Verse,2018,"Bitten by a radioactive spider in the subway, ...",97,93,387,PG,"action, adventure, fantasy, comedy, kids and f...",...,0,1,0,0,0,0,0,190200000.0,-0.0258,0
3,8.315430,73,Coco,2017,Despite his family's generations-old ban on mu...,97,94,347,PG,"comedy, music, animation, kids and family, adv...",...,0,1,0,0,0,0,0,210500000.0,0.8074,1
4,8.040924,216,Logan,2017,"In the near future, a weary Logan (Hugh Jackma...",93,90,418,R,"adventure, action, fantasy",...,0,0,0,1,0,0,0,226300000.0,0.6983,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,8.157822,140,Unforgiven,1992,When prostitute Delilah Fitzgerald (Anna Thoms...,96,93,106,R,western,...,0,0,0,1,0,0,0,100000000.0,0.2579,7
248,8.439455,48,Once Upon a Time in the West,1969,There's a single piece of land around Flagston...,95,95,65,PG-13,western,...,0,0,1,0,0,0,0,NaN,-0.8151,0
249,8.409954,55,Django Unchained,2012,"Two years before the Civil War, Django (Jamie ...",87,91,291,R,"western, action, drama",...,0,0,0,1,0,0,0,162800000.0,-0.6249,3
250,8.001911,249,Dances With Wolves,1990,A Civil War soldier develops a relationship wi...,83,87,76,PG-13,"drama, history, western",...,0,0,1,0,0,0,0,184000000.0,-0.0258,2
251,8.190189,128,The Kid,2019,In 1879 Rio and his teenage sister go on the r...,44,46,45,R,"western, drama",...,0,0,0,1,0,0,0,1500000.0,-0.4939,0

In [12]:

# Create a function that takes in a list of crew members and returns the total number of Oscars won by them
def count_oscars_crew(crew_list):
    # Concatenate all the crew members into a single string
    crew_str = ','.join(crew_list)
    # Split the string into a list of individual crew members
    crew_members = crew_str.split(',')
    # Return the total number of Oscars won by the crew members
    return oscar_count_df[oscar_count_df['name'].isin(crew_members)]['oscars'].sum()

# Apply the count_oscars function to the "crew" column in the "df" dataframe and store the result in a new column called "crew_oscars"
df['crew_oscars'] = df['crew'].str.split(',').apply(count_oscars_crew)

,imdb_score,place,title,year,synopsis,critic_score,people_score,total_reviews,rating,genre,...,PG,PG-13,R,TV14,TVMA,TVPG,boxoffice,sentiment_score,director_oscars,crew_oscars
0,8.303145,78,Avengers: Endgame,2019,"Adrift in space with no food or water, Tony St...",94,90,538,PG-13,"sci fi, adventure, action, fantasy",...,0,1,0,0,0,0,858400000.0,-0.7650,0,2
1,8.063783,199,Mad Max: Fury Road,2015,"Years after the collapse of civilization, the ...",97,86,427,R,"adventure, action",...,0,0,1,0,0,0,153600000.0,-0.7650,2,1
2,8.340630,66,Spider-Man: Into the Spider-Verse,2018,"Bitten by a radioactive spider in the subway, ...",97,93,387,PG,"action, adventure, fantasy, comedy, kids and f...",...,1,0,0,0,0,0,190200000.0,-0.0258,0,0
3,8.315430,73,Coco,2017,Despite his family's generations-old ban on mu...,97,94,347,PG,"comedy, music, animation, kids and family, adv...",...,1,0,0,0,0,0,210500000.0,0.8074,1,1
4,8.040924,216,Logan,2017,"In the near future, a weary Logan (Hugh Jackma...",93,90,418,R,"adventure, action, fantasy",...,0,0,1,0,0,0,226300000.0,0.6983,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,8.157822,140,Unforgiven,1992,When prostitute Delilah Fitzgerald (Anna Thoms...,96,93,106,R,western,...,0,0,1,0,0,0,100000000.0,0.2579,7,7
248,8.439455,48,Once Upon a Time in the West,1969,There's a single piece of land around Flagston...,95,95,65,PG-13,western,...,0,1,0,0,0,0,NaN,-0.8151,0,2
249,8.409954,55,Django Unchained,2012,"Two years before the Civil War, Django (Jamie ...",87,91,291,R,"western, action, drama",...,0,0,1,0,0,0,162800000.0,-0.6249,3,2
250,8.001911,249,Dances With Wolves,1990,A Civil War soldier develops a relationship wi...,83,87,76,PG-13,"drama, history, western",...,0,1,0,0,0,0,184000000.0,-0.0258,2,2
251,8.190189,128,The Kid,2019,In 1879 Rio and his teenage sister go on the r...,44,46,45,R,"western, drama",...,0,0,1,0,0,0,1500000.0,-0.4939,0,2

In [15]:
#Fix collection so that it is 1 or 0 if it is part of a collection or not. 
df['collection'] = df['collection'].fillna('').astype(bool).astype(int)

In [14]:
# Get a list of all column names in the dataframe
column_names = df.columns.tolist()

# Print the list of column names
print(column_names)

['imdb_score', 'place', 'title', 'year', 'synopsis', 'critic_score', 'people_score', 'total_reviews', 'rating', 'genre', 'director', 'writer', 'runtime', 'collection', 'crew', 'history', 'fantasy', 'other', 'comedy', 'sports and fitness', 'western', 'action', 'kids and family', 'anime', 'biography', 'adventure', 'animation', 'horror', 'music', 'crime', 'sci fi', 'romance', 'musical', 'documentary', 'mystery and thriller', 'gay and lesbian', 'war', 'drama', 'G', 'NC-17', 'PG', 'PG-13', 'R', 'TV14', 'TVMA', 'TVPG', 'boxoffice', 'sentiment_score', 'director_oscars', 'crew_oscars']

In [22]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Get the design matrix (X) for the model
X = model.model.exog

# Calculate the VIF for each independent variable
vif = [variance_inflation_factor(X, i) for i in range(X.shape[1])]

# Print the results
for i, name in enumerate(model.model.exog_names):
    print(f"{name}: VIF = {vif[i]:.2f}")

const: VIF = 20797.64
imdb_score: VIF = 1.61
year: VIF = 3.49
critic_score: VIF = 2.34
people_score: VIF = 2.53
total_reviews: VIF = 2.52
runtime: VIF = 1.61
collection: VIF = 1.87
history: VIF = nan
fantasy: VIF = nan
other: VIF = nan
comedy: VIF = 1.17
sports and fitness: VIF = nan
western: VIF = 1.07
action: VIF = 1.39
kids and family: VIF = nan
anime: VIF = nan
biography: VIF = nan
adventure: VIF = nan
animation: VIF = nan
horror: VIF = nan
music: VIF = nan
crime: VIF = nan
sci fi: VIF = 1.15
romance: VIF = 1.12
musical: VIF = 1.13
documentary: VIF = nan
mystery and thriller: VIF = 1.26
gay and lesbian: VIF = nan
war: VIF = nan
drama: VIF = 1.32
G: VIF = 1.92
NC-17: VIF = nan
PG: VIF = 2.41
PG-13: VIF = 2.59
R: VIF = 2.65
TV14: VIF = nan
TVMA: VIF = nan
TVPG: VIF = nan
sentiment_score: VIF = 1.15
director_oscars: VIF = 1.68
crew_oscars: VIF = 1.71

/home/justinzhou/.local/lib/python3.6/site-packages/statsmodels/regression/linear_model.py:1715: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - self.ssr/self.centered_tss

In [32]:
#REGRESSION
import statsmodels.api as sm



# Define the independent variables and the dependent variable
X = df[['imdb_score', 'year', 'critic_score', 'people_score', 'total_reviews',
        'runtime', 'collection', 'history', 'fantasy', 'other', 'comedy', 'sports and fitness',
        'western', 'action', 'kids and family', 'anime', 'biography', 'adventure', 'animation',
        'horror', 'music', 'crime', 'sci fi', 'romance', 'musical', 'documentary',
        'mystery and thriller', 'gay and lesbian', 'war', 'drama', 'G', 'NC-17', 'PG', 'PG-13',
        'R', 'TV14', 'TVMA', 'TVPG', 'sentiment_score', 'director_oscars', 'crew_oscars']]
y = df['boxoffice']

# Import the necessary modules
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the input features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Set up the Lasso regression model
lasso = Lasso(alpha=0.1)

# Fit the Lasso model to the training data
lasso.fit(X_train_scaled, y_train)

# Print the coefficients and intercept
print("Intercept:", lasso.intercept_)
for i, name in enumerate(X.columns):
    print(f"{name}: {lasso.coef_[i]:.3f}")

# Predict on the test data and calculate R-squared
y_pred = lasso.predict(X_test_scaled)
r2 = lasso.score(X_test_scaled, y_test)
print("R-squared:", r2)

Intercept: 144425122.11538455
imdb_score: -2855596.784
year: 45948363.393
critic_score: -12908653.348
people_score: -231403.502
total_reviews: 70917753.479
runtime: 36988518.001
collection: 5547889.817
history: 0.000
fantasy: 0.000
other: 0.000
comedy: -4437546.336
sports and fitness: 0.000
western: 0.000
action: 0.000
kids and family: 0.000
anime: 0.000
biography: 0.000
adventure: 0.000
animation: 0.000
horror: 0.000
music: 0.000
crime: 0.000
sci fi: -26259713.475
romance: 974921.430
musical: 0.000
documentary: 0.000
mystery and thriller: 3287972.909
gay and lesbian: 0.000
war: 0.000
drama: -18207225.873
G: 61081766.094
NC-17: 0.000
PG: -3165786.026
PG-13: 56408913.202
R: -29331227.096
TV14: 0.000
TVMA: 0.000
TVPG: 0.000
sentiment_score: -2640336.323
director_oscars: 29647353.940
crew_oscars: -32375758.515
R-squared: 0.5322272818491054

/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/_coordinate_descent.py:532: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1.2220882437557248e+16, tolerance: 364554756107024.06
  positive)

In [35]:
#Save Coefficients
# Extract the coefficients for each independent variable
coefficients = lasso.coef_

# Create a list of the independent variable names
variable_names = list(X.columns)

# Create a dataframe with the variable names and coefficients
coefficients_df = pd.DataFrame({'Variable': variable_names, 'Coefficient': coefficients})

# Save the dataframe as a CSV file
coefficients_df.to_csv('lasso_coefficients.csv', index=False)

In [36]:
df

,imdb_score,place,title,year,synopsis,critic_score,people_score,total_reviews,rating,genre,...,PG,PG-13,R,TV14,TVMA,TVPG,boxoffice,sentiment_score,director_oscars,crew_oscars
0,8.303145,78,Avengers: Endgame,2019,"Adrift in space with no food or water, Tony St...",94,90,538,PG-13,"sci fi, adventure, action, fantasy",...,0,1,0,0,0,0,858400000.0,-0.7650,0,2
1,8.063783,199,Mad Max: Fury Road,2015,"Years after the collapse of civilization, the ...",97,86,427,R,"adventure, action",...,0,0,1,0,0,0,153600000.0,-0.7650,2,1
2,8.340630,66,Spider-Man: Into the Spider-Verse,2018,"Bitten by a radioactive spider in the subway, ...",97,93,387,PG,"action, adventure, fantasy, comedy, kids and f...",...,1,0,0,0,0,0,190200000.0,-0.0258,0,0
3,8.315430,73,Coco,2017,Despite his family's generations-old ban on mu...,97,94,347,PG,"comedy, music, animation, kids and family, adv...",...,1,0,0,0,0,0,210500000.0,0.8074,1,1
4,8.040924,216,Logan,2017,"In the near future, a weary Logan (Hugh Jackma...",93,90,418,R,"adventure, action, fantasy",...,0,0,1,0,0,0,226300000.0,0.6983,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,8.026293,226,Groundhog Day,1993,"Phil (Bill Murray), a weatherman, is out to co...",96,88,84,PG,romance,...,1,0,0,0,0,0,162600.0,-0.8225,0,1
247,8.157822,140,Unforgiven,1992,When prostitute Delilah Fitzgerald (Anna Thoms...,96,93,106,R,western,...,0,0,1,0,0,0,100000000.0,0.2579,7,7
249,8.409954,55,Django Unchained,2012,"Two years before the Civil War, Django (Jamie ...",87,91,291,R,"western, action, drama",...,0,0,1,0,0,0,162800000.0,-0.6249,3,2
250,8.001911,249,Dances With Wolves,1990,A Civil War soldier develops a relationship wi...,83,87,76,PG-13,"drama, history, western",...,0,1,0,0,0,0,184000000.0,-0.0258,2,2
251,8.190189,128,The Kid,2019,In 1879 Rio and his teenage sister go on the r...,44,46,45,R,"western, drama",...,0,0,1,0,0,0,1500000.0,-0.4939,0,2

In [37]:
# Save the dataframe as a CSV file
df.to_csv('version2df.csv', index=False)